---
- name: install apache2 on slave1
  hosts: slave1
  become: true
  tasks:
    - name: apt-update
      apt:
        update_cache: yes
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start service
      systemd:
        name: apache2
        state: restarted

- name: install nginx on slave2
  hosts: slave2
  become: true
  tasks:
    - name: apt-update
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start service
      systemd:
        name: nginx
        state: restarted
