---
- name: install apache2 on localhost
  hosts: localhost
  become: true
  tasks:
    - name: apt-update
      apt:
        update_cache: yes
    - name: install apache2
      apt:
        name: apache2
        state: present
    - name: start service
      systemd:
        name: apache2
        state: restarted

