---
- name: install nginx on localhost
  hosts: localhost
  become: true
  tasks:
    - name: run apt-update
      apt:
        update_cache: yes
    - name: install nginx
      apt:
        name: nginx
        state: present
    - name: start service
      systemd:
        name: nginx
        state: restarted
